### ISSUE TITLE
Absurd fixed size of mkvtoolnix-gui.exe up to +2000p width, it eats the entire screen

### ISSUE THREAD

**Issue by ElektroStudios** [mbunkus/mkvtoolnix#1349]
Today I've downloaded the new version 8.1.0 x64, I'm familiar with  the usage of mmg.exe but when I run it it advertised me about it is considered deprecated and I should use the new gui...

Well, the problem begins when I run the new gui, mkvtoolnix-gui.exe.

In my screen, which is 1920x1080, when I run the program it auto-resizes the form up to exactlly 2324x629 pixels, which is totally absurd and I don't understand why happens this, maybe are you using some custom logic to auto-resize the form at startup?, in that case need to know that the algorithm is totally bugged.

Also the width of the form is not resizable, it is fixed, why?, so I cannot temporally fix this, the author of the application could just assign a minimim size property and let the end-user resize the width.

I just report this because in my conditions the program is very disgusting, it eats all myascreen so I still preffer to use the old mmg.exe which does not have any kind of problem like this, please, fix this issue or don't remove mmg.exe from nfuture releases until this is fixed.

How I reproduce the problem?:
1 - Using Windows 8.1 x64.
2 - Just run the program and will auto-resize...
3 - I'm not sure what other conditions could be involved, maybe I should say that I'm using a dual monitor and, in the control panel of Windows, I set to clone the screens (don't extend the screen).

Thanks for read.

**Comment by mbunkus** [comment]
I don't force any size at startup. However, in release 8.1.0 there are several controls that don't deal well with overly long file names if there's no space where the file name can be word-wrapped. This could lead to very wide windows that couldn't be made smaller. This particular issue has been fixed since, see #1314.

Please give a new [pre-build](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) a try which include said fix. Note that the GUI remembers the previous size and restores it on startup, so even with the new pre-build you'll probably see a huge window when it starts, but the you should be able to make it smaller.

**Comment by ElektroStudios** [comment]
Thanks for support. but I tried "mkvtoolnix-64bit-8.1.0-build20150703-813-55d4c1f.7z" and the problem is the same, resolution is not fixed, and form width is not resizable; an image:

![captura 2](https://cloud.githubusercontent.com/assets/13082613/8633354/c48a6e34-27c3-11e5-8bfa-6d01d681cbcb.png)

**Comment by ElektroStudios** [comment]
I just noted now that this issue only happens when a non-aero theme is set on the system.

**Comment by mbunkus** [comment]
What do you mean by »non-Aero theme«? Where would I get such a theme to try this with? Cause none of the themes coming with Windows 8.1 shows such a behavior.

**Comment by ElektroStudios** [comment]
Ok sorry I'll explain it better.

As many Windows users, I used UltraUXThemePatcher to patch the uxtheme.dll to be able use 3rd party visual themes (that's what I mean when saying non-Aero theme):
http://www.syssel.net/hoefs/software_uxtheme.php?lang=en#down

Then, I noted that this issue only happens when using that kind of themes, this is a visual theme that produces that resolution issue:
http://www.mediafire.com/download/222l389b2nu4wfx/Gnommit+theme+for+Windows+8.1.rar
(note that the theme was designed for Windows 8.1, maybe using it in previous version could cause conflicts like a blue-screen)

Could you test your software when that theme is activated?.

Please, before considering this issue as too odd or singular, I will note that I'll never got this kind of issue with any other software than MKV Toolnix, and I'm using 3rd party visual themes since windows VISTA.

I'm really interested in to find a solution for this.

Thanks for your time, patience, and effort with bug reports of your software.

**Comment by mbunkus** [comment]
I can reproduce the issue with the theme you've linked, but not with other random themes using UltraUX, e.g. [Dark Lion](http://sagorpirbd.deviantart.com/art/Dark-Lion-for-Win-8-8-1-Final-430847005). So this seems to be an issue with that particular theme. I'm not willing to invest any time in such an incompatibility. Sorry.

**Comment by mbunkus** [comment]
![with-dark-lion-theme](https://cloud.githubusercontent.com/assets/414282/8633428/2928cc60-27c8-11e5-9f4b-ec345572c757.png)

**Comment by mbunkus** [comment]
To be clear: this seems to be an issue triggered by your particular theme, not by UltraUX in general. Maybe that theme is enforcing some kind of minimum width for certain UI elements, e.g. the progress bars shown in the GUI's status bars. Anyway, this is just guesswork, and again, nothing that I'm going to invest time in.

**Comment by ElektroStudios** [comment]
@mbunkus

Thankyou again, I understand you will not investigate it, but, could you do a little favor?, just could you try that gnommit theme with the progressbars of mkvtoolnix disabled (I mean set the progressbars to non-visible)? that will really help me to find a possible issue with that in the theme.

**Comment by mbunkus** [comment]
Hiding the status bar progress widget does improve things. Now the maximum width is constrained by the single progress bar shown on the »job output« tab.

If I hide the progress bar on the »job output« tab, too, then the minimum width is the one I would expect it to be and consistent with other themes.

Note that the initial window size was still huge – probably because those progress bar controls get created but are hidden immediately. It can be made small after hiding them, though.

So yes, it does seem to be connected.

**Comment by ElektroStudios** [comment]
Thanks so much. nd sorry I thinked the problem was because MKV Toolnix GUI components or a resize logic or something else.

**Comment by mbunkus** [comment]
You're welcome, and no problem at all.
