### ISSUE TITLE
Grey frames with HEVC videos

### ISSUE THREAD

**Issue by Fenntil** [mbunkus/mkvtoolnix#1547]
Using mkvtoolnix GUI v8.6.1, when I load a file with encoded HEVC video, and simply remux the file, the new file shows a grey thumbnail in windows explorer and when I read the file (with MPC-HC) each time I jump (backward or forward) I get a grey frame and sometimes artifacts too (grey squares), but those grey frames don't show when I don't jump. The original file does not do this. I tried to remux just the video in case the problem would come from the other tracks, but it does just the same.

**Comment by mbunkus** [comment]
Thanks for the report. Is your source file an MP4 file? If so this might be the same issue as #1543.

**Comment by Fenntil** [comment]
Yes, format is mpeg-4, in an m4v container.

**Comment by mbunkus** [comment]
Can you please upload one such file (the one before remuxing) to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can take a look? Thanks.

**Comment by Fenntil** [comment]
File sent : (...)the beginning.m4v

**Comment by mbunkus** [comment]
Thanks. This is definitely a different issue than the aforementioned one. I'll investigate it.

**Comment by mbunkus** [comment]
I've just implemented a potential fix. What I've done in terms of analysis is:

  1. remux the M4V to Matroska with v8.6.1
  2. extract the video track from the file created in 1. to a raw HEVC elementary stream
  3. remuxed the raw elementary stream created in 2. to another Matroska file
  4. compared the frame types, sizes, checksums of the files created in 1. and 3.

This has shown that key frame indicators were off by one frame hinting at an issue with edit lists. This I have potentially fixed.

I'm being cautious here as I haven't been able to reproduce Explorer showing gray/distorted thumbnails with the Matroska file created with v8.6.1; the thumbnails were OK. A file created with the fixed version will also show with a proper thumbnail, and playback works nicely including seeking.

Can you please give the [new pre-builds I've created](https://mkvtoolnix.download/windows/pre/) a try and report back here? Build numbers that include the fix are 1066 for the 32bit version and 1067 for the 64bit version. Thanks.

**Comment by Fenntil** [comment]
Sorry, but I can't seem to find build 1066 or 1067 in the indicated folders? In the 64bits folder it jumps from 1065 to 1071.

I installed the lastest build (1075) and did a simple remux of the same file I sent you, and the problem is still exactly the same in appearance here.

**Comment by Fenntil** [comment]
An interesting thing : I updated my K-lite codec pack Mega from 11.2 to 11.8 and now seeking the file does not show any grey frame; the thumbnail however remains grey.

**Comment by mbunkus** [comment]
Thanks for giving it a try and sorry for the confusion. I had to remove several builds (among them 1066 and 1067) due to a nasty memory leak that I've fixed since.

Unfortunately none of the currently available builds contain your particular fix as I had developed that fix on a different branch.

Therefore… here's yet another build, this time with the fix included: [pre-builds 1076, 1077](https://mkvtoolnix.download/windows/pre/).

**Comment by Fenntil** [comment]
OK, the problem of grey frames seems to be fixed!

However, there's something I just noticed : the aspect ratio of the original video (4:3) is changed to 3:2 (with no change in resolution) though I have not selected anything (just loaded the file, and clicked 'start muxing').

So, I forced the aspect ratio to 4:3 in Video properties. But it's still not exaclty the same as the original : the display is a few pixels larger...

**Comment by mbunkus** [comment]
Thanks for the confirmation.

**Comment by mbunkus** [comment]
Even though the aspect ratio is another thing and would have better had its own issue I've fixed the handling since. [Pre-builds 1078, 1079](https://mkvtoolnix.download/windows/pre/) are up that include said fix as well.

**Comment by Fenntil** [comment]
Works great now, thanks! And keep up the good job with mkvtoolnix!

**Comment by mbunkus** [comment]
Thanks again for the confirmation. And for the praise :)
