### ISSUE TITLE
Help install version 5.8.0

### ISSUE THREAD

**Issue by LeoCBS** [mbunkus/mkvtoolnix#1852]
Hi, i am trying to compile and install version 5.8.0.. but after pass autogen.. configure.. without errors.. rake install got this error:

    mkdir -p -- /usr/local/share/locale/zh_TW/LC_MESSAGES
    /usr/bin/install -c -m 644 po/cs.mo /usr/local/share/locale/cs/LC_MESSAGES/mkvtoolnix.mo
    /usr/bin/install: cannot stat 'po/cs.mo': No such file or directory

I am try install in ubuntu 14.04..

Thanks for help..

**Comment by mkver** [comment]
Do you want to install version 5.8 because all later versions procude files which cannot be seeked by some (probably hardware) player you use? If so, it is better to disable the creation of these elements with the "engage"-switches described [here](https://github.com/mbunkus/mkvtoolnix/wiki/Improving-playback-compatibility-with-players). These elements broke some bad demultiplexers who didn't ignore what they didn't know (even VLC was affected, but has been fixed a long time ago).
Version 5.8 is no longer supported, so don't expect Moritz to invest any time in this.

**Comment by mbunkus** [comment]
I'm sorry, but I don't support such old versions in general. The current version doesn't compile on 14.04 anymore either due to the compiler not supporting required features of C++,but you should be able to compile 9.6.0.

**Comment by LeoCBS** [comment]
Just for help some one else that have problem with player compatibility..

I built and installed version 5.8.0 on one docker image:

https://github.com/LeoCBS/mkv-subtitle

**Comment by mkver** [comment]
Just out of curiosity: Why don't you just use the engage-switches with a recent version of MKVToolNix? You can even configure it to automatically add the switches to the command line.

**Comment by LeoCBS** [comment]
I tried to use one recent version using engage-switches as link posted above.. but my player still can't play movie correctly. Movie stopped playing suddenly..
